/**
 * dsh-sister Web client (hand-rolled module-loader bundle).
 *
 * A classic script registering with the web shell through
 * `window.__ModuleLoader__.load({ id, factory })`. Only `react` is imported;
 * no JSX, no TypeScript, no build step — plain `React.createElement`.
 *
 * Registers:
 *  - `conversation.input.right` "speak" toggle (🔊) — gates to sister-agent
 *    sessions (isSisterSession: `useSessions` agentPreset === 'sister').
 *  - `shell.overlay` cheer chip — a small floating card that appears when a
 *    cheer is fired (scheduled daily / /cheer / the cheer tool) and fades out.
 *
 * Speech: the browser's built-in Web Speech API plays on the USER'S machine —
 * cross-platform (macOS, Windows, Chrome, Edge, Safari), no server TTS. The
 * client auto-reads EVERY assistant reply aloud (1s beat so the text shows
 * first), honors explicit speak requests from the `sisterSpeak` projection,
 * and prefers soft female English voices.
 *
 * @module dsh-sister/client
 */
window.__ModuleLoader__.load({
  id: 'dsh-sister',
  factory: (require) => {
    var module = { exports: {} }
    var exports = module.exports
    Object.defineProperty(exports, Symbol.toStringTag, { value: 'Module' })

    var React = require('react')

    // ---- tiny shared store: cheer chip + voice picker + latest projection --
    var store = { cheer: null, sessionId: undefined, voiceOpen: false, listeners: [] }
    /** The plugin's apply() context, captured for component-side host calls. */
    var pluginCtx = null
    function emit() {
      for (var i = 0; i < store.listeners.length; i++) store.listeners[i]()
    }
    function subscribe(fn) {
      store.listeners.push(fn)
      return function () {
        var at = store.listeners.indexOf(fn)
        if (at >= 0) store.listeners.splice(at, 1)
      }
    }
    function setStoreVoiceOpen(open) {
      store.voiceOpen = open
      emit()
    }

    // ---- helpers -----------------------------------------------------------
    function h(type, props) {
      var children = Array.prototype.slice.call(arguments, 2)
      return React.createElement.apply(React, [type, props].concat(children))
    }

    // ---- styles (theme-variable driven) ------------------------------------
    var PANEL_CARD = {
      border: '1px solid var(--dsw-border-color, rgba(128,128,128,.25))',
      borderRadius: 8,
      padding: '10px 14px',
      fontSize: 13,
      lineHeight: 1.5,
      background: 'var(--dsw-alias-bg-overlay, var(--dsw-surface-color, #ffffff))',
      boxShadow: '0 8px 30px rgba(0,0,0,.25)',
    }

    // ---- TTS ---------------------------------------------------------------
    // The sister's voice is generated by Qwen3-TTS (VoiceDesign) on the host
    // machine. The client asks the host for a WAV via /dsh-sister/tts and
    // plays it in an <audio> element — sound comes out of the user's own
    // machine. Utterances queue: the next one starts when the current one
    // ends, so rapid-fire cheers never overlap.

    var STYLE_KEY = 'dsh-sister.style'

    /** Voice-design instruct presets (natural-language voice description). */
    var STYLES = {
      paimon: {
        label: '✨ 派蒙风 — 尖尖脆脆的萝莉音',
        instruct: '体现撒娇稚嫩的萝莉女声，音调偏高且起伏明显，营造出黏人、做作又刻意卖萌的听觉效果。说话语气活泼俏皮，像动画里的小精灵。',
      },
      cute: {
        label: '🌸 软萌可爱',
        instruct: '温柔甜美的少女音，音调柔和偏高，说话软糯撒娇，语气温暖亲切，带着浅浅的笑意。',
      },
      genki: {
        label: '⚡ 元气少女',
        instruct: '活泼元气的高中少女音，清亮明快，语速稍快，充满阳光与干劲，经常带着惊叹和感叹词。',
      },
      cool: {
        label: '🎧 清冷御姐',
        instruct: '清冷柔和的成年女声，语速平缓，语调平稳优雅，带着淡淡的温柔和从容。',
      },
    }
    var DEFAULT_STYLE = 'paimon'

    function savedStyle() {
      try {
        var s = window.localStorage.getItem(STYLE_KEY)
        return s !== null && STYLES[s] !== undefined ? s : null
      } catch (e) {
        return null
      }
    }
    function saveStyle(name) {
      try {
        window.localStorage.setItem(STYLE_KEY, name)
      } catch (e) {}
    }
    function styleInstruct(name) {
      var s = STYLES[name]
      return s ? s.instruct : STYLES[DEFAULT_STYLE].instruct
    }

    // ---- audio queue -------------------------------------------------------
    // Main queue: assistant-message readings and cheer speak events play in
    // order, one at a time, so rapid-fire speech never overlaps.
    var audioQueue = []
    var audioPlaying = false
    function playNextAudio() {
      if (audioPlaying || audioQueue.length === 0) return
      audioPlaying = true
      var item = audioQueue.shift()
      var audio = new Audio(item.url)
      audio.onended = function () {
        audioPlaying = false
        playNextAudio()
      }
      audio.onerror = function () {
        audioPlaying = false
        playNextAudio()
      }
      audio.play().catch(function () {
        audioPlaying = false
        playNextAudio()
      })
    }

    // ---- style preview (voice picker) --------------------------------------
    // Preview requests are INDEPENDENT of the main queue: clicking a style
    // cancels the previous unfinished preview request AND the previous preview
    // audio, then plays the new one immediately when it arrives. This keeps
    // the picker snappy even though each generation takes a few seconds.
    var previewController = null
    var previewAudio = null
    function stopPreview() {
      if (previewController !== null) {
        try { previewController.abort() } catch (e) {}
        previewController = null
      }
      if (previewAudio !== null) {
        try { previewAudio.pause() } catch (e) {}
        previewAudio = null
      }
    }
    /** Request + play one style preview. Returns a promise resolving when the
     * request settles (not when audio finishes). Never throws. */
    function previewStyle(key) {
      stopPreview()
      var controller = new AbortController()
      previewController = controller
      var instruct = styleInstruct(key)
      return fetch('/dsh-sister/tts?text=' + encodeURIComponent(PREVIEW_TEXT) + '&instruct=' + encodeURIComponent(instruct), {
        signal: controller.signal,
      })
        .then(function (res) {
          if (!res.ok) throw new Error('tts ' + res.status)
          return res.blob()
        })
        .then(function (blob) {
          if (previewController !== controller) return // superseded
          var url = URL.createObjectURL(blob)
          var audio = new Audio(url)
          previewAudio = audio
          return audio.play().catch(function () {})
        })
        .catch(function () {
          // aborted (superseded) or unreachable — silent, the UI clears busy
        })
    }

    /** Strip markdown-ish markup so the speech is clean prose. */
    function speakable(text) {
      return String(text)
        .replace(/\[([^\]]*)\]\([^)]*\)/g, '$1')
        .replace(/[*_`#>|]/g, '')
        .replace(/\s+/g, ' ')
        .trim()
    }

    /** Speak text with the Qwen3-TTS voice. Requests the WAV from the host
     * (which proxies to the local TTS service), then plays it in order.
     * @param text - the text to speak.
     * @param style - voice style key (paimon/cute/genki/cool); saved when given. */
    function speakBrowser(text, style) {
      if (typeof window === 'undefined' || typeof window.fetch !== 'function') return
      var clean = speakable(text)
      if (!clean) return
      if (style !== undefined && style !== null) saveStyle(style)
      var key = style || savedStyle() || DEFAULT_STYLE
      var instruct = styleInstruct(key)
      // 30s cap so a busy TTS service can't stall the queue forever.
      fetch('/dsh-sister/tts?text=' + encodeURIComponent(clean) + '&instruct=' + encodeURIComponent(instruct), {
        signal: AbortSignal.timeout(30000),
      })
        .then(function (res) {
          if (!res.ok) throw new Error('tts ' + res.status)
          return res.blob()
        })
        .then(function (blob) {
          var url = URL.createObjectURL(blob)
          audioQueue.push({ url: url })
          playNextAudio()
        })
        .catch(function () {
          // TTS service unreachable or timed out — fall back to nothing (silent).
        })
    }

    /** Text of an assistant node from its text blocks. Harness blocks use
     * `kind` ('text' = visible text, 'reasoning' = Think chain-of-thought);
     * accept the legacy `type` spelling too. */
    function assistantNodeText(node) {
      var blocks = node.blocks || []
      return blocks
        .filter(function (b) { return b !== null && (b.kind === 'text' || b.type === 'text') && typeof b.text === 'string' })
        .map(function (b) { return b.text })
        .join('\n')
        .trim()
    }

    /** The real conversation node behind a chat-store view wrapper. Chat
     * store entries are `{ key, kind, id, target, data }` — the assistant
     * step keeps its final message in `data.finalNode`. Returns the node
     * itself when it is already a raw conversation node. */
    function unwrapNode(node) {
      if (node === null || node === undefined) return null
      var d = node
      if (d.data !== undefined && d.data !== null && d.blocks === undefined && d.seq === undefined && d.kind !== 'assistant') {
        d = d.data
      }
      if (d !== null && d !== undefined && d.finalNode !== undefined && d.finalNode !== null) {
        d = d.finalNode
      }
      return d
    }

    /** Latest assistant message text from the conversation snapshot, or null.
     * Checks both the legacy top-level `nodes` array and the `chat` store. */
    function latestAssistantText(session) {
      if (session === null || session === undefined) return null
      if (Array.isArray(session.nodes)) {
        for (var i = session.nodes.length - 1; i >= 0; i--) {
          var n = unwrapNode(session.nodes[i])
          if (n === null || n.kind !== 'assistant') continue
          var text = assistantNodeText(n)
          if (text) return { seq: n.seq, text: text }
        }
      }
      if (session.chat !== null && session.chat !== undefined) {
        var order = session.chat.order || []
        var nodes = session.chat.nodes
        var get = typeof nodes.get === 'function' ? function (id) { return nodes.get(id) } : function (id) { return nodes[id] }
        for (var j = order.length - 1; j >= 0; j--) {
          var m = unwrapNode(get(order[j]))
          if (m === null || m.kind !== 'assistant') continue
          var t = assistantNodeText(m)
          if (t) return { seq: m.seq, text: t }
        }
      }
      return null
    }

    /** Sister-only gate: the host rows publish process-globally, so the
     * projection reaches every session — the toggle must additionally check
     * that THIS session actually runs the sister agent preset. */
    function isSisterSession(props) {
      if (props.sessionId === undefined || typeof props.useSessions !== 'function') return false
      var preset = props.useSessions(function (s) { return s.byId[props.sessionId]?.agentPreset })
      return preset === 'sister'
    }

    // ---- speak toggle ------------------------------------------------------
    function SpeakToggle(props) {
      var value = (props.useProjection ? props.useProjection('sisterSpeak') : null) || { speakEnabled: true, lastSpoken: null, lastCheer: null }
      var state = React.useState(value.speakEnabled !== false)
      React.useEffect(function () {
        state[1](value.speakEnabled !== false)
      }, [value.speakEnabled])
      var session = props.session || (props.useSession ? props.useSession(function (s) { return s }) : null)
      var isSister = isSisterSession(props)
      // Explicit speak requests (speak tool / /speak <text>).
      var spokenSeqRef = React.useRef(0)
      var spokenTextRef = React.useRef(null)
      React.useEffect(function () {
        var last = value.lastSpoken
        if (last === null || last === undefined) return
        if (last.seq <= spokenSeqRef.current) return
        spokenSeqRef.current = last.seq
        if (value.speakEnabled === false) return
        spokenTextRef.current = String(last.text || '')
        speakBrowser(last.text)
      }, [value.lastSpoken, value.speakEnabled])
      // Auto-read EVERY assistant reply (the sister always talks). Waits a
      // beat so the learner sees the text before the sound starts. The
      // pending timer lives in a ref so later snapshot re-renders do NOT
      // cancel it — only a genuinely new message supersedes the pending one.
      var spokenMsgRef = React.useRef(null)
      var pendingSpeakRef = React.useRef(null)
      React.useEffect(function () {
        if (!isSister) return
        if (value.speakEnabled === false) return
        var msg = latestAssistantText(session)
        if (msg === null) return
        if (spokenMsgRef.current !== null && spokenMsgRef.current.seq === msg.seq && spokenMsgRef.current.text === msg.text) return
        if (pendingSpeakRef.current !== null && pendingSpeakRef.current.seq === msg.seq && pendingSpeakRef.current.text === msg.text) return
        if (spokenTextRef.current !== null && spokenTextRef.current === msg.text) return
        if (pendingSpeakRef.current !== null) {
          clearTimeout(pendingSpeakRef.current.timer)
          pendingSpeakRef.current = null
        }
        var timer = setTimeout(function () {
          pendingSpeakRef.current = null
          spokenMsgRef.current = msg
          speakBrowser(msg.text)
        }, 1000)
        pendingSpeakRef.current = { seq: msg.seq, text: msg.text, timer: timer }
      }, [session, value.speakEnabled, isSister])
      // Cheer chip: surface a fired cheer into the shared store.
      React.useEffect(function () {
        var cheer = value.lastCheer
        if (cheer === null || cheer === undefined) return
        store.cheer = { text: String(cheer.text || ''), at: Date.now(), sessionId: props.sessionId }
        store.sessionId = props.sessionId
        emit()
      }, [value.lastCheer])
      React.useEffect(function () {
        return function () {
          if (pendingSpeakRef.current !== null) clearTimeout(pendingSpeakRef.current.timer)
        }
      }, [])
      if (!isSister) return null
      var enabled = state[0]
      return h('div', { style: { display: 'flex', alignItems: 'center', gap: 2 } },
        h('button', {
          onClick: function () { setStoreVoiceOpen(!store.voiceOpen) },
          title: '听一下再选妹妹的声音 — pick & preview the sister\'s voice',
          'aria-label': 'Sister voice picker',
          style: {
            background: 'none', border: 'none', cursor: 'pointer',
            fontSize: 14, padding: '2px 4px',
            color: 'var(--dsw-text-color, inherit)',
          },
        }, '🎤'),
        h('button', {
          onClick: function () {
            var next = !enabled
            state[1](next)
            try {
              var sessions = pluginCtx.get('sessions')
              var binding = sessions === undefined ? undefined : sessions.binding(props.sessionId)
              if (binding !== undefined && typeof binding.session.command === 'function') {
                binding.session.command('/speak ' + (next ? 'on' : 'off')).catch(function () {})
              }
            } catch (e) {}
          },
          title: enabled ? 'Sister voice is on — click to mute' : 'Sister voice is muted — click to enable',
          'aria-label': 'Sister speak toggle',
          style: {
            background: 'none', border: 'none', cursor: 'pointer',
            fontSize: 14, padding: '2px 6px',
            color: enabled ? 'var(--dsw-text-color, inherit)' : '#8e8e8e',
            textDecoration: enabled ? 'none' : 'line-through',
          },
        }, '🔊'),
      )
    }

    // ---- voice style picker panel ------------------------------------------
    // Centered modal listing the Qwen3-TTS voice-design styles. Click a row:
    // it previews the style immediately AND locks the choice.
    var PICKER_WRAP = {
      position: 'fixed', left: '50%', top: '50%', transform: 'translate(-50%, -50%)',
      zIndex: 1000, width: 'min(560px, 94vw)', maxWidth: 560,
    }
    var PICKER_BACKDROP = {
      position: 'fixed', inset: 0, zIndex: 999,
      background: 'rgba(0, 0, 0, 0.35)',
    }
    var PICKER_ROW = {
      display: 'flex', alignItems: 'center', justifyContent: 'space-between',
      width: '100%', textAlign: 'left', padding: '8px 10px', borderRadius: 6,
      cursor: 'pointer', marginBottom: 2,
      border: '1px solid var(--dsw-border-color, rgba(128,128,128,.25))',
      background: 'var(--dsw-surface-color, transparent)',
      color: 'var(--dsw-text-color, inherit)', fontSize: 13,
    }
    var PREVIEW_TEXT = '嗨嗨！我是你的妹妹呀～你喜欢我的声音吗？嘿嘿！'
    function VoicePicker() {
      var openState = React.useState(store.voiceOpen)
      var busyState = React.useState(null) // style key currently generating
      React.useEffect(function () {
        return subscribe(function () {
          openState[1](store.voiceOpen)
        })
      }, [])
      if (!openState[0]) return null
      var saved = savedStyle()
      var keys = ['paimon', 'cute', 'genki', 'cool']
      var busy = busyState[0]
      var rows = keys.map(function (key) {
        var active = saved === key
        var generating = busy === key
        var label = STYLES[key].label
        return h('button', {
          key: key,
          disabled: busy !== null && busy !== key,
          onClick: function () {
            saveStyle(key)
            busyState[1](key)
            previewStyle(key).then(function () {
              // Clear busy only if this style is still the current one.
              busyState[1](function (current) { return current === key ? null : current })
            })
          },
          style: Object.assign({}, PICKER_ROW, active ? { border: '2px solid #f39c12' } : {}, generating ? { opacity: .55, cursor: 'wait' } : {}),
        },
          h('span', { style: { fontWeight: active ? 700 : 400 } },
            (active ? '✓ ' : '') + (generating ? '⏳ 生成中… ' : '') + label),
        )
      })
      return h(React.Fragment, null,
        h('div', { style: PICKER_BACKDROP, onClick: function () { setStoreVoiceOpen(false) } }),
        h('div', { style: PICKER_WRAP },
          h('div', { style: Object.assign({}, PANEL_CARD, { maxHeight: '86vh', overflow: 'auto' }), className: 'dsh-sister-voice-picker' },
            h('div', { style: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 6 } },
              h('span', { style: { fontWeight: 600 } }, '🎤 妹妹的音色 — click to preview & select'),
              h('button', { onClick: function () { setStoreVoiceOpen(false) }, style: { background: 'none', border: 'none', cursor: 'pointer', fontSize: 13 } }, '✕'),
            ),
            h('div', { style: { fontSize: 11, opacity: .6, marginBottom: 8 } },
              '点一下试听，自动记住你最后选的音色（Qwen3-TTS 生成，几秒钟）。Click a style to hear it — your last pick is remembered.'),
            rows,
          ),
        ),
      )
    }

    // ---- cheer chip --------------------------------------------------------
    // A small floating card that pops up when a cheer fires and fades out.
    function CheerChip() {
      var state = React.useState(store.cheer)
      React.useEffect(function () {
        return subscribe(function () {
          state[1](store.cheer)
        })
      }, [])
      var cheer = state[0]
      var visibleState = React.useState(false)
      React.useEffect(function () {
        if (cheer === null || cheer === undefined || typeof cheer.text !== 'string' || cheer.text === '') {
          visibleState[1](false)
          return
        }
        // Only show when the cheering session is the one being viewed.
        visibleState[1](true)
        var timer = setTimeout(function () { visibleState[1](false) }, 9000)
        return function () { clearTimeout(timer) }
      }, [cheer])
      if (!visibleState[0] || cheer === null) return null
      return h('div', {
        style: { position: 'fixed', left: 16, bottom: 96, zIndex: 1000, maxWidth: 380, width: 'calc(100vw - 32px)' },
      },
        h('div', { style: Object.assign({}, PANEL_CARD, { borderLeft: '3px solid #f39c12' }), className: 'dsh-sister-cheer-chip' },
          h('div', { style: { fontWeight: 600, marginBottom: 2, color: 'var(--dsw-text-color, inherit)' } }, '💛 Sister says…'),
          h('div', { style: { whiteSpace: 'pre-wrap', wordBreak: 'break-word', color: 'var(--dsw-text-color, inherit)' } }, cheer.text),
        ),
      )
    }

    // ---- plugin ------------------------------------------------------------
    exports.name = 'dsh-sister/client'
    exports.inject = ['slots', 'conversation']
    exports._test = { assistantNodeText, latestAssistantText, unwrapNode, speakable, STYLES, DEFAULT_STYLE, styleInstruct, savedStyle }
    exports.apply = function (ctx) {
      var slots = ctx.get('slots')
      if (slots === undefined) return
      pluginCtx = ctx
      slots.inject('conversation.input.right', function () {
        return slots.register(
          { name: 'conversation.input.right', id: 'dsh-sister-speak', order: 9, label: function () { return 'Speak' } },
          SpeakToggle,
        )
      })
      slots.inject('shell.overlay', function () {
        return slots.register({ name: 'shell.overlay', id: 'dsh-sister-cheer-chip', order: 40 }, CheerChip)
      })
      slots.inject('shell.overlay', function () {
        return slots.register({ name: 'shell.overlay', id: 'dsh-sister-voice-picker', order: 45 }, VoicePicker)
      })
    }

    return module.exports
  },
})
